global using Microsoft.EntityFrameworkCore;
global using SistemaEstoque.Domain;
global using SistemaEstoque.App.Contratos;
global using Microsoft.Extensions.DependencyInjection;
global using SistemaEstoque.App;
global using SistemaEstoque.App.Context;
global using SistemaEstoque.App.Services;
global using SistemaEstoque.Pages.Categorias;
global using SistemaEstoque.Pages.Produtos;
